// DB USUARIOS Y TABLA USUARIOS

CREATE DATABASE IF NOT EXISTS hotel_waldorf
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE hotel_waldorf;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NULL,
    rol ENUM('ADMIN', 'RECEPCIONISTA') NOT NULL DEFAULT 'RECEPCIONISTA',
    estado ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);